services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: exp2-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    external: true
    name: travelhubsecnet
