services:
  mongodb:
    image: mongo:7.0
    container_name: exp2-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local

networks:
  default:
    external: true
    name: travelhubsecnet
